### ISSUE TITLE
How do i get the right version of mimikatz

### ISSUE THREAD

**Issue by Xbit53** [makozort/RDwindowspasswordgrabber#1]
C:\WINDOWS\system32>%TEMP%\pw.exe > c:\pwlog.txt & type pwlog.txt;
This version of C:\Users\myname\AppData\Local\Temp\pw.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
The system cannot find the file specified.

the error i get. The mimikatz link i used was the default github link(https://github.com/gentilkiwi/mimikatz.git) and i think that is the problem....it downloads and saves it as pw.exe. can i get a different link for mimikatz

**Comment by JackMako** [comment]
you will have to create your own download link. I recommend [anonfiles.](https://anonfiles.com/) Keep in mind you will have to get a new download link from this every now and then
